// Generated by CoffeeScript 1.4.0
(function() {

  if (!Meteor.isClient) {
    return;
  }

  Meteor.windowtest.numberOfWindowsToOpen(2);

  Tinytest.addAsync("sample test", function(test, onComplete) {
    test.equal(5, 5);
    return onComplete();
  });

}).call(this);
